name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Do you want to deploy to production?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  deploy:
    if: ${{ github.event.inputs.deploy == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to main
        run: echo "deploying to main"
